/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 56905939c85562917ef8a6cfeae4fe71)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	CONTACT_DB: D1Database;
	EMDASH_DEPLOYMENT_TARGET: "preview";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMDASH_DEPLOYMENT_TARGET">> {}
}
