/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 76089f334a51de4e17ac9ee1371dcaf6)
interface __BaseEnv_CloudflareEnv {
	CONTACT_DB: D1Database;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		CONTACT_DB: D1Database;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
