import type { LegacyAssetFetcher } from './legacy-article-asset.ts';

type RedirectRule = { pattern: RegExp; destination: string; status: number };
type HeaderRule = { pattern: RegExp; headers: Array<[string, string]> };

/** Only the local path and trailing-splat syntax used by the checked-in files is admitted. */
function pathPattern(path: string): RegExp {
  if (!/^\/[^?#\\]*$/.test(path) || path.startsWith('//') || /[:]/.test(path)) {
    throw new Error('Unsupported public response path pattern: ' + path);
  }
  if (path.includes('*') && (!path.endsWith('/*') || path.slice(0, -1).includes('*'))) {
    throw new Error('Unsupported public response splat: ' + path);
  }
  const escaped = path.replace(/[.+?^$(){}|[\]\\]/g, '\\$&').replace('*', '.*');
  return new RegExp('^' + escaped + '$');
}

function redirectRules(source: string): RedirectRule[] {
  return source
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => {
      const [path, destination, statusText, extra] = line.split(/\s+/);
      const status = Number(statusText);
      if (
        extra ||
        !destination?.startsWith('/') ||
        destination.startsWith('//') ||
        /[?#\\:*]/.test(destination) ||
        ![301, 302, 303, 307, 308].includes(status)
      ) {
        throw new Error('Unsupported public redirect rule: ' + line);
      }
      return { pattern: pathPattern(path), destination, status };
    });
}

function headerRules(source: string): HeaderRule[] {
  const rules: HeaderRule[] = [];
  for (const line of source.split(/\r?\n/)) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    if (!/^\s/.test(line)) {
      rules.push({ pattern: pathPattern(line.trim()), headers: [] });
      continue;
    }
    const match = /^\s+([A-Za-z0-9-]+):\s*(.+)$/.exec(line);
    if (!match || !rules.length) throw new Error('Unsupported public header rule: ' + line);
    rules[rules.length - 1].headers.push([match[1], match[2]]);
  }
  return rules;
}

/** Leave API, authentication, and signed preview policies to their own handlers. */
function isPublicPath(pathname: string): boolean {
  let path = pathname;
  try {
    for (let i = 0; i < 3; i++) path = decodeURIComponent(path);
  } catch {
    return false;
  }
  path = path.replace(/\/+/g, '/').toLowerCase();
  return (
    !/^\/(?:_emdash|api|_actions)(?:\/|$)/.test(path) &&
    !/^\/(?:(?:en|zh|ja|ko|ru|es|pt|fr)\/)?cms-preview(?:\/|$)/.test(path)
  );
}

/** Static-asset configuration does not apply to responses generated by Astro's Worker. */
export function createPublicResponseParity(redirectSource: string, headerSource: string) {
  const redirects = redirectRules(redirectSource);
  const headers = headerRules(headerSource);

  return {
    redirect(request: Request): Response | undefined {
      const url = new URL(request.url);
      if (!isPublicPath(url.pathname)) return undefined;
      const rule = redirects.find((candidate) => candidate.pattern.test(url.pathname));
      if (!rule) return undefined;
      // Preserve a submitted body even if a legacy rule was originally a 301/302.
      const status = request.method === 'GET' || request.method === 'HEAD' ? rule.status : 308;
      return new Response(null, {
        status,
        headers: { Location: rule.destination + url.search },
      });
    },

    applyHeaders(request: Request, response: Response): Response {
      const pathname = new URL(request.url).pathname;
      if (!isPublicPath(pathname)) return response;
      // The Response-copy constructor preserves the platform's streaming/encoding metadata.
      const result = new Response(response.body, response);
      if (result.status >= 400 && !result.headers.has('Cache-Control')) {
        result.headers.set('Cache-Control', 'no-store');
      }
      for (const rule of headers) {
        if (!rule.pattern.test(pathname)) continue;
        for (const [name, value] of rule.headers) {
          const current = result.headers.get(name);
          if (name.toLowerCase() === 'x-frame-options' && value.toUpperCase() === 'DENY') {
            result.headers.set(name, value);
          } else if (!current) {
            result.headers.set(name, value);
          }
        }
      }
      return result;
    },
  };
}

/** Match Pages' canonical slash redirect only when the destination is a real legacy asset. */
export async function fetchPublicCanonicalRedirect(
  request: Request,
  assets: LegacyAssetFetcher
): Promise<Response | undefined> {
  if (request.method !== 'GET' && request.method !== 'HEAD') return undefined;
  const url = new URL(request.url);
  if (!isPublicPath(url.pathname) || url.pathname.endsWith('/') || /\.[^/]*$/.test(url.pathname)) return undefined;
  const originalPath = url.pathname;
  const destination = url.pathname + '/' + url.search;
  url.pathname += '/';
  const candidate = await assets.fetch(new Request(url, request));
  let redirectsToOriginalAsset = false;
  const location = candidate.headers.get('Location');
  if ([301, 307, 308].includes(candidate.status) && location) {
    try {
      // Auto HTML handling can serve /zh.html at /zh and redirect /zh/ back
      // there. Astro serves the same asset at /zh/, which is Pages' canonical.
      const target = new URL(location, url);
      redirectsToOriginalAsset = target.origin === url.origin && target.pathname === originalPath;
    } catch {
      // An invalid or unrelated redirect does not prove that a static asset exists.
    }
  }
  const exists =
    (candidate.status >= 200 && candidate.status < 300) || candidate.status === 304 || redirectsToOriginalAsset;
  await candidate.body?.cancel();
  if (!exists) return undefined;
  return new Response(null, { status: 308, headers: { Location: destination } });
}

/** Canonicalize only successfully rendered CMS blog pages absent from the legacy asset inventory. */
export function canonicalizeCmsBlogResponse(request: Request, response: Response): Response {
  if ((request.method !== 'GET' && request.method !== 'HEAD') || response.status !== 200) return response;
  if (!/^\s*text\/html(?:\s*;|$)/i.test(response.headers.get('Content-Type') ?? '')) return response;

  const url = new URL(request.url);
  // Exact public route shapes only. Encoded aliases, private routes, and unknown slugs retain their response.
  if (!/^\/(?:(?:zh|ja|ko|ru|es|pt|fr)\/)?blog(?:\/[a-z0-9]+(?:-[a-z0-9]+)*)?$/.test(url.pathname)) {
    return response;
  }
  return new Response(null, {
    status: 308,
    headers: { Location: `${url.pathname}/${url.search}`, 'Cache-Control': 'no-store' },
  });
}

/** The generated sitemap index/chunks must win over EmDash's dynamic sitemap-[collection].xml route. */
export async function fetchGeneratedSitemapAsset(
  request: Request,
  assets: LegacyAssetFetcher
): Promise<Response | undefined> {
  if (request.method !== 'GET' && request.method !== 'HEAD') return undefined;
  const pathname = new URL(request.url).pathname;
  if (pathname !== '/sitemap-index.xml' && !/^\/sitemap-(?:0|[1-9][0-9]*)\.xml$/.test(pathname)) {
    return undefined;
  }
  // Pass the original request through, including query and conditional headers. A missing
  // generated asset stays a 404 rather than falling through to EmDash's collection route.
  return assets.fetch(request);
}
